### PR TITLE
Added checkPreAuth call before creating authenticated token

### PR DESCRIPTION
**Pull request by alex-ception**
This add the support off enabled, expired, locked statuses when working with AdvancedUserInterface

### CODE REVIEW

**Comment by rudott** [comment]
@alex-ception can you tell me why this PR is closed?

By adding this check it's possible to add the default checks isAccountNonLocked, isEnabled & isAccountNonExpired by using the AdvancedUserInterface.

**Comment by alex-ception** [comment]
I don't know, and I don't care anymore. This protocol is fucked up, so was this bundle.
Good luck :D

**Comment by tmilos** [comment]
This lib is not maintained anymore since there's a new version for almost a year now in https://github.com/lightSAML/SpBundle

**Comment by rudott** [comment]
@tmilos I know :-) I found this PR and was wondering why this was closed, maybe there was a good reason to do this..

**Pull request closed without merging**
