### PR TITLE
Allow setting cert_file and key_file to null

### PR DESCRIPTION
**Pull request by victorjacobs**
The setup in which we use this bundle require disabling and enabling SAML message signing depending on which server the application is deployed. I wanted to do this by putting the cert_file and key_file as parameters in parameters.yml, set them to null for our demo and staging server and set them to real values on production. Currently this is not allowed as both parameters have a 'cannotBeEmpty()' set on them.
I don't think that allowing this will cause any problems since this is essentially the same as omitting the 'signing' section of the configuration.

### CODE REVIEW

**Comment by i3or1s** [comment]
Until this is sorted you can always override the config.
http://symfony.com/doc/current/book/templating.html#overriding-bundle-templates

**Comment by victorjacobs** [comment]
Why not simply allow nulls in the configuration? I believe this is a cleaner solution.

**Comment by i3or1s** [comment]
Documentation part
https://www.oasis-open.org/committees/download.php/35711/sstc-saml-core-errata-2.0-wd-06-diff.pdf

## 5 SAML and XML Signature Syntax and Processing

- A SAML protocol message arriving at a destination from an entity other than the originating sender
SHOULD be signed by the sender.
- Profiles MAY specify alternative signature mechanisms such as S/MIME or signed Java objects that contain SAML documents. Caveats about retaining context and interoperability apply. XML
Signatures are intended to be the primary SAML signature mechanism, but this specification
attempts to ensure compatibility with profiles that may require other mechanisms.
- Unless a profile specifies an alternative signature mechanism, any XML Digital Signatures MUST be enveloped.

I am not sure on how to approach this subject since they are using a lot of MAY.
I guess it is ok for it to not to be signed (though it seams a bit strange to me).

Any other opinions on this subject?

**Comment by victorjacobs** [comment]
I completely agree that you should sign SAML messages. However, our client simply told us that 'it would be easier to simply disable signing on staging servers, because creating certificates is a hassle and we'll only do it for the production server'.
Also, the current implementation does allow to disable signing by simply omitting the 'signing' section of the configuration (since the 'signing' array node is not required in SamlSpFactory.php). But moving these to Symfony's parameters.yml and then setting them to null on certain servers is not possible. Removing the 'cannotBeEmpty()' has the same result as omitting the entire 'signing' section.
I have this change deployed on our staging/demo servers, with the parameters set to null and it works as I would expect.

**Pull request merged**
