### PR TITLE
Enhancement - Remove usage of deprecated SecurityContextInterface.

### PR DESCRIPTION
**Pull request by BernardoSilva**
Applied changes to remove deprecated code on `SecurityController` according to:
http://symfony.com/blog/new-in-symfony-2-6-security-component-improvements

### CODE REVIEW

**Comment by tmilos** [comment]
You must also change composer.json and increase the symfony version to ~2.6.

**Comment by stof** [comment]
A better solution would be to support both the new way and the old one, to keep the compatibility with the 2.3 LTS

**Comment by BernardoSilva** [comment]
Yup @stof , I agree with you.
I am just waiting for https://github.com/aerialship/SamlSPBundle/pull/71 to be merged and after that I can test on Symfony2.3 and update this PR with something backward compatible with 2.3
I have a project in 2.3 where I want to use this bundle, just need MongoDB support first.

**Comment by tmilos** [comment]
This should be BC with symfony 2.3 
@BernardoSilva Is there something more you wish to do now, since #71 is merged?

**Comment by BernardoSilva** [comment]
@tmilos I am now using latest version of the bundle, just found 1 issue until now and already created PR https://github.com/aerialship/SamlSPBundle/pull/88 .
I think this is BC with Symfony 2.3, I am just using the `Security::AUTHENTICATION_ERROR` instead of `SecurityContextInterface::AUTHENTICATION_ERROR`.

I am using symfony2.3 and when I checked `SecurityContextInterface::AUTHENTICATION_ERROR` : 
```php
/// vendor/symfony/symfony/src/Symfony/Component/Security/Core/SecurityContextInterface.php 
const AUTHENTICATION_ERROR = Security::AUTHENTICATION_ERROR;
```

**Comment by tmilos** [comment]
This aerialship/lightsaml will support only symfony <2.8 and no deprecation notices will be fixed, ref #110

A new [lightsaml/lightsaml] library and it's [SpBunle](https://github.com/lightSAML/SpBundle) support symfony 2.3 - 3.0

**Pull request closed without merging**
